apiVersion: v1
kind: Secret
metadata:
  name: saas-app-secrets
  namespace: saas-operator
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:joe301162@postgres-external.coffeeshop.svc.cluster.local:5432/projeto_saas?schema=public"
  JWT_SECRET: "troque-este-segredo"
  ADMIN_PASSWORD: "301162"
