apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-api
  namespace: saas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-api
  template:
    metadata:
      labels:
        app: saas-api
    spec:
      initContainers:
        - name: prisma-migrate
          image: REPLACE_API_IMAGE
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: saas-app-secrets
          command: ["sh", "-lc"]
          args:
            - |
              cd /app/apps/api && npx prisma migrate deploy

      containers:
        - name: api
          image: REPLACE_API_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001

          envFrom:
            - secretRef:
                name: saas-app-secrets
            - configMapRef:
                name: saas-app-config

          readinessProbe:
            httpGet:
              path: /api/plans
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/plans
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 20
