apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-web
  namespace: saas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-web
  template:
    metadata:
      labels:
        app: saas-web
    spec:
      containers:
        - name: web
          image: REPLACE_WEB_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "/api"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
