apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-web
  namespace: saas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-web
  template:
    metadata:
      labels:
        app: saas-web
    spec:
      containers:
        - name: web
          image: REPLACE_WEB_IMAGE
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: saas-web
  namespace: saas-operator
spec:
  type: NodePort
  selector:
    app: saas-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32080
