apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas
  namespace: saas-operator
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: operator.rushconnect.com.br
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: saas-api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-web
                port:
                  number: 3000
